image: Visual Studio 2017

environment:
  host: x86_64-pc-windows-msvc
  matrix:
    - platform: x86_64
      target: x86_64-pc-windows-msvc
      channel: nightly
    - platform: x86_64
      target: x86_64-pc-windows-msvc
      channel: stable
    - platform: arm64
      target: aarch64-pc-windows-msvc
      channel: nightly
matrix:
  allow_failures:
    - channel: stable
    - platform: arm64

install:
    - appveyor DownloadFile https://win.rustup.rs/ -FileName rustup-init.exe
    - rustup-init -yv --default-toolchain %channel% --default-host %host%
    - set PATH=%PATH%;%USERPROFILE%\.cargo\bin;%APPVEYOR_BUILD_FOLDER%
    - ps: $Env:PKG_CONFIG_ALLOW_CROSS=1
    - rustc -vV
    - cargo -vV
    - rustup target add %target%
    - git submodule update --init

build_script:
    - cargo build --release --target=%target%

test_script:
    - cargo test --target=%target% --verbose

artifacts:
    - path: target\$(target)\release\*.*
      name: rust-av-$(platform)
